import { SignIn, SignInButton, SignOutButton, useUser , UserButton} from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { Helmet } from "react-helmet";
import dayjs from 'dayjs'

import { api } from "~/utils/api";

import { useRouter } from "next/router";








const ProfilePage: NextPage = () => {
  // const {data} = api.example.getAll.useQuery()

  const user = useUser()

  const router = useRouter()

  const { data, isLoading } = api.post.getAll.useQuery()

  const { mutate } = api.post.create.useMutation()

  console.log(router.query.id)


  



  return (
    <>
      <Head>
        <title>{`User Posts`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bug">Bug Renport</div>
      <div className="page home">



        <Helmet>
          <meta charSet="utf-8" />
          <title>HOME | Anon-Thoughts</title>
          {/* <link rel="canonical" href="" /> */}
        </Helmet>


        <p> </p>

       
      </div>


    </>

  )
}


export default ProfilePage;
