import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Audio } from 'react-loader-spinner'
import { Helmet } from "react-helmet";
import { api } from "~/utils/api";
import AnonCards from "./components/AnonCards";

const Home: NextPage = () => {
  // const {data} = api.example.getAll.useQuery()
  const { data, isLoading } = api.post.getAll.useQuery()

  const user = useUser()
  if(!data) return <div>Something went wrong...</div>

  



  console.log("The logged data is : ", data)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bug">Bug Renport</div>
      <div className="page home">



        <Helmet>
          <meta charSet="utf-8" />
          <title>HOME | Anon-Thoughts</title>
          {/* <link rel="canonical" href="" /> */}
        </Helmet>

        <nav>
          <div className="flex justify-between items-center">
            <div>

              <Link className="homes-create" href="/">Home</Link>
              <Link href="/create" className="create-tot">Create Thoughts</Link>
            </div>
            <div className="">
              {!user.isSignedIn && <div className="create-tot"><SignInButton /></div>}
              {!!user.isSignedIn && <div className="create-tot"><SignOutButton /></div>}

            </div>
            {/* <Link to="/about" className="create-tot">About Anon</Link> */}


          </div>
        </nav>
        <div className="fixed-header">
          {/* <h2 className="homes">Thoughts</h2> */}
          <div className="underline"></div>




        </div>
        <div className="loading">
          <Audio
            height="100"
            width="100"
            color="#5e10ee"
            ariaLabel="audio-loading"
            // className="loader"

            wrapperStyle={{
              position: 'absolute',
              left: '45%',
              zIndex: "1000",
              width: "50px",
              height: "50px",
              marginBottom: "40px",


            }}
            wrapperClass="wrapper-class"
            visible={isLoading}

          />
        </div>




        <div className="smoothie-grid">
          {data && data.map(anon => (
            // console.log(anon)

            <AnonCards key={anon.post.id} post={anon.post} author={anon.author} />

          ))}
        </div>
      </div>


    </>

  )
}
{/* <main className="h-full h-screen">
        <div className="">

        <div className=''>

         {!user.isSignedIn && <div><SignInButton/></div>}
         {!!user.isSignedIn && <div><SignOutButton/></div>}

        </div>

        <div>

          { data && data.map(post => (<div key={post.id}> {post.content}</div>))}
        </div>

        </div> */}

// </main>


export default Home;
